  name: Test Cron
on:
  schedule:
    - cron: "* * * * *"  # هذا يعني تشغيل كل دقيقة
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print time
        run: echo "The job is working at $(date)"
        
